/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.56
 * Generated at: 2014-12-07 14:58:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class signin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	String errorMsg = null;

	Connection conn = null;
	PreparedStatement stmt = null;
	ResultSet rs = null;

	// DB 접속을 위한 준비
	String dbUrl = "jdbc:mysql://localhost:3306/movieholic";
	String dbUser = "kbc13";;
	String dbPassword = "a12345";

	//사용자 정보를 위한 변수 초기화
	String userid = "";
	String name = "";
	String password = "";
	String usernumber="";
	
	
	//post
	String id = request.getParameter("id");	
	String pwd = request.getParameter("pwd");
	//관리자 아이디, 비밀번호
	String managerid = "";
	String managerpwd = "";
	int a =10;
	boolean signin = false;
	String actionurl ="";
	try {
		Class.forName("com.mysql.jdbc.Driver");

		//DB 접속
		conn = DriverManager.getConnection(dbUrl, dbUser, dbPassword);
		stmt = conn.prepareStatement("SELECT * FROM members where usernumber=1");
		rs=stmt.executeQuery();
		rs.next();
		managerid=rs.getString("userid");
		managerpwd=rs.getString("pwd");
		//질의준비
		stmt = conn
				.prepareStatement("SELECT * FROM members ");		
		//수행
		rs = stmt.executeQuery();

		while(rs.next()) {
			userid = rs.getString("userid");
			name = rs.getString("name");
			password = rs.getString("pwd");
			usernumber=rs.getString("usernumber");
			
			
			if (userid.equals(id) && password.equals(pwd)) {
				// 로그인 성공
				session.setAttribute("userId", userid);
				session.setAttribute("userName", name);
				session.setAttribute("userNumber", usernumber);
				session.setAttribute("userPwd",password);
				signin = true;
				actionurl="./index.jsp";
				
				
			 if(managerid.equals(id)&& managerpwd.equals(pwd)){
				actionurl="./manager/index_manager.jsp";
				signin = true;
				session.setAttribute("userName", "관리자");
				}
			}
		}
	} catch (SQLException e) {
		errorMsg = "SQL 에러 : " + e.getMessage();
	} finally {
		//리소스를 종료
		if (rs != null)try {rs.close();} catch (SQLException e) {}
		if (stmt != null)try {stmt.close();} catch (SQLException e) {}
		if (conn != null)try {conn.close();} catch (SQLException e) {}
	}


      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>signin</title>\r\n");
      out.write("\t<link href=\"css/main.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-latest.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"wrap\">\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Share/Header.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t\t");

				if (request.getMethod() == "POST") {
					if (id == null || pwd == null || id.length() == 0
							|| pwd.length() == 0) {
			
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"error\">아이디와 비밀번호를 입력하세요.</div>\r\n");
      out.write("\t\t\t");

					} else if (signin) {
						// 로그인 성공
						response.sendRedirect(actionurl);
						
					} else {
			
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"error\">아이디나 비밀번호가 잘못되었습니다.</div>\r\n");
      out.write("\t\t\t");

					}

				}
			
      out.write("\r\n");
      out.write("\t<div class=\"content\">\t\r\n");
      out.write("\t\t<div class=\"signin\">\r\n");
      out.write("\t\t\t<form method=\"post\">\r\n");
      out.write("\t\t\t\t<br> \r\n");
      out.write("\t\t\t\tID: <input type=\"text\" name=\"id\">\r\n");
      out.write("\t\t\t\tPassword: <input type=\"password\" name=\"pwd\"> \r\n");
      out.write("\t\t\t\t<input type=\"submit\" value=\"Sign in\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Share/footer.jsp", out, false);
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
