/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.56
 * Generated at: 2014-12-07 04:12:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Share;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;

public final class Header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");


	String [][] navbarImages  = {{"images/boxoffice.png","./boxoffice.jsp"},{"images/review.png","./review.jsp"},{"images/director.png","./director.jsp"}
															,{"images/filmaward.png","./filmaward.jsp"}};


	String currentMenu = request.getParameter("current");
	
	String username=null;
	String userid=null;
	boolean flag = false;
	if(session.getAttribute("userName")!=null){
		username=(String)session.getAttribute("userName");
		userid=(String)session.getAttribute("userId");
		flag=true;
		
	}

      out.write("\r\n");
      out.write("<!--  Navbar -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"top\">\r\n");
      out.write("\t<div id=\"memberbar\">\r\n");
      out.write("\r\n");
      out.write("\t\t");
	if (flag) { 
      out.write("\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t");
	out.println("<p class='name'>"+username+"</p>"); 
      out.write("\r\n");
      out.write("\t\t<div class=\"memberbar_inner\">\r\n");
      out.write("\t\t\t<a href='./signout.jsp'>sign out</a> <a href='./mypage.jsp'>my\r\n");
      out.write("\t\t\t\tpage</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t");
 } else{ 
      out.write("\r\n");
      out.write("\t\t<div class=\"memberbar_inner\">\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<br> <a href='./signup.jsp'>sign up</a> <a href='./signin.jsp'>sign\r\n");
      out.write("\t\t\t\tin</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t");
 }
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"left\">\r\n");
      out.write("\t<div id=\"title\">\r\n");
      out.write("\t\t<a href=\"index.jsp\"><img src=\"./images/logo.png\"></a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"menubar\" style=\"float: left\">\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t");

							for(String menuItem[] : navbarImages) {
								if(currentMenu != null ) {
									out.println("<li class = 'active'>");
									}
									else{
										out.println("<li class = ''>");
									}

									out.println("<a href ='"+menuItem[1]+"'><img src=" +menuItem[0]+ "></a>");

									out.println("</li>");
							}
						
      out.write("\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
